version: '3.8'

services:
  postgres:
    image: postgres:15
    restart: unless-stopped
    environment:
      POSTGRES_DB: loteria
      POSTGRES_USER: root
      POSTGRES_PASSWORD: rootpass
    ports:
      - "5442:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - loteria

  adminer:
    image: adminer
    restart: always
    ports:
      - "5555:8080"
    networks:
      - loteria

volumes:
  pgdata:

networks:
  loteria:
